### ISSUE TITLE
Add Some Documentation on the code.

### ISSUE THREAD

**Issue by Madonahs** [jumaallan/android-mpesa-api#14]
**Is your feature request related to a problem? Please describe.**

Not based on any problem but just some nice documentation of the code.

**Describe the solution you'd like**

The best approach is to comment on the code using Javadoc explaining what some of the methods do. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jumaallan** [comment]
@Madonahs 
I will work on this, but feel free to make a pull request also. We can always have better minds going through the code and also helping out 🥇

**Comment by Madonahs** [comment]
Awesome, Once that is done i can look into it. I found it hard to understand what you mean by LMNexpress and others -- 👍  as a new comer.

**Comment by Madonahs** [comment]
@jumaallan Thanks, I will close this issue and surely work on another one :)
