### ISSUE TITLE
AccountReference character limit.

### ISSUE THREAD

**Issue by nyandika** [jumaallan/android-mpesa-api#16]
There is a **12 character** limit for the account reference.

Funny thing is the response returned says request is being processed, however the actual push is not made to device. Was trying this out today on the Safaricom portal earlier, probably a bug on their end.

**Comment by jumaallan** [comment]
Hi @nyandikadon 
Safaricom had issued a maintainance notice, probably that is why you did not get the STKPush. But I just tested it out on my device, it works

**Comment by nyandika** [comment]
Hi @jumaallan I have tested with the following values where one account reference has 12 characters and the other has 14 characters. Could you kindly confirm if both return a push or its just me and a bad day. Thanks

# 12 characters
{
   "BusinessShortCode": "174379",
   "Password": "MTc0Mzc5YmZiMjc5ZjlhYTliZGJjZjE1OGU5N2RkNzFhNDY3Y2QyZTBjODkzMDU5YjEwZjc4ZTZiNzJhZGExZWQyYzkxOTIwMTgwNzE2MTQwMzUy",
   "Timestamp": "20180716140352",
   "TransactionType": "CustomerPayBillOnline",
   "Amount": "10",
   "PartyA": "2547********",
   "PartyB": "174379",
   "PhoneNumber": "2547********",
   "CallBackURL": "http://mycallbackurl.com/checkout.php",
   "AccountReference": "457A2715F2D9",
   "TransactionDesc": "Mpesa Express STK Push test"
}

# 14 characters
{
   "BusinessShortCode": "174379",
   "Password": "MTc0Mzc5YmZiMjc5ZjlhYTliZGJjZjE1OGU5N2RkNzFhNDY3Y2QyZTBjODkzMDU5YjEwZjc4ZTZiNzJhZGExZWQyYzkxOTIwMTgwNzE2MTQwOTA5",
   "Timestamp": "20180716140909",
   "TransactionType": "CustomerPayBillOnline",
   "Amount": "10",
   "PartyA": "2547********",
   "PartyB": "174379",
   "PhoneNumber": "2547********",
   "CallBackURL": "http://mycallbackurl.com/checkout.php",
   "AccountReference": "0FD70C4EEA3B09",
   "TransactionDesc": "Mpesa Express STK Push test"
}

**Comment by jumaallan** [comment]
@nyandikadon 
I have seen the issue. Its not working with 12 and 14 characters. But works with 10 characters. This is a bug on the Safaricom end.
Could you test out with 10 characters?
