### ISSUE TITLE
Getting records of people who have made payments

### ISSUE THREAD

**Issue by pkavoo** [jumaallan/android-mpesa-api#19]
Is it possible to retrieve transaction history?

**Comment by jumaallan** [comment]
@pkavoo 
Sorry for taking time to get back to you. Unfortunately Safaricom does not provide this yet. There is no API to get this data, but you can see it on your MPESA Portal

**Comment by makunomark** [comment]
Hey @jumaallan is this issue still open?

**Comment by jumaallan** [comment]
@makunomark 

Hey Mark. If you look at the Safaricom documentation, under C2B, they only push transactions to you. You need to have a setup to save and query for all transactions. Simple example is, when you set a callback url, and it gets notifications from Safaricom, save the records. This allows you to poll for transactions later on on your system. If you are trying to implement something different from this let me know.

**Comment by jumaallan** [comment]
To close this issue 👍
