### ISSUE TITLE
Can't resolve imports, or use current implementation in README

### ISSUE THREAD

**Issue by JobGetabu** [jumaallan/android-mpesa-api#37]
updated to v1.0.2
- Can't resolve `Daraja.Builder`
- Can't import `Environment.SANDBOX` previously from` Env.SANDBOX`

```
@Provides
    @Singleton
    Daraja providesDaraja() {
        return Daraja.Builder(Config.CONSUMER_KEY, Config.CONSUMER_SECRET)
                .setBusinessShortCode(Config.BUSINESS_SHORTCODE)
                .setPassKey(AppUtils.getPassKey())
                .setTransactionType(Config.ACCOUNT_TYPE)
                .setCallbackUrl(Config.CALLBACK_URL)
                .setEnvironment(Environment.SANDBOX)
                .build();
    }
```

**Comment by jumaallan** [comment]
@JobGetabu Will be updating this repo this week - make it simpler, also try to introduce various DI options on how to set it up and the bare implementation without any DI option

**Comment by jumaallan** [comment]
@JobGetabu Will look into this. It's over a year, but I am reworking the repo again

**Comment by jumaallan** [comment]
This ticket will be closed when we update the Quick Start section on the README. The idea is simple - remove the DI setup on the sample app code, to make it easier for users to use the library in whatever way works best for them
