### ISSUE TITLE
Docs Add: code of conduct and contributor guidelines

### ISSUE THREAD

**Issue by orama254** [jumaallan/android-mpesa-api#43]
**Is your feature request related to a problem? Please describe.**
making it smooth for newbies to contribute to the project in accordance to Github's [recommended community standards](https://opensource.guide/) 

**Describe the solution you'd like**
Add code of conduct and contributor guidelines file to align with Github's [recommended community standards](https://opensource.guide/)

**Describe alternatives you've considered**
N/A

**Additional context: screenshot**
![android_mpesa_api](https://user-images.githubusercontent.com/50571688/95179590-810f0c00-07c9-11eb-9af1-2c0dd7e41651.JPG)

I'd be delighted to work on this issue if accepted

**Comment by jumaallan** [comment]
Feel free

**Comment by jumaallan** [comment]
Closing this issue @orama254
