### ISSUE TITLE
Kotlin Support

### ISSUE THREAD

**Issue by jumaallan** [jumaallan/android-mpesa-api#5]
Add Kotlin Support and Examples to this project - Enhancements

**Comment by JobGetabu** [comment]
Waiting for Kotlin support....

**Comment by jumaallan** [comment]
@JobGetabu 
Hi, Will start working on this. But feel free to create a pull request and I will be glad to merge it 👍

**Comment by jumaallan** [comment]
Linked to [Issue 24](https://github.com/jumaallan/AndroidMPesaAPI/issues/24)

To close this Issue
