### ISSUE TITLE
JCenter Migration

### ISSUE THREAD

**Issue by etonotieno** [jumaallan/android-mpesa-api#52]
https://developer.android.com/studio/build/jcenter-migration

**Comment by jumaallan** [comment]
@wangerekaharun 

Can we look into this as well?

**Comment by wangerekaharun** [comment]
Sure we can.


@jumaallan let me know the next steps on this.

**Comment by jumaallan** [comment]
We need to maybe create some tickets on the Project tab to track tickets and work done

**Comment by wangerekaharun** [comment]
This is probably has a bit of admin-related tasks too.

**Comment by jumaallan** [comment]
When publishing. Let me check and send an invite to you as well
