### ISSUE TITLE
Generate Library Code Documentation

### ISSUE THREAD

**Issue by jumaallan** [jumaallan/android-mpesa-api#64]
Since we have Dokka plugin setup on the repo, it makes sense to add code documentation

**Comment by jumaallan** [comment]
We need to consider adding documentation when working on the library module, to make it easy to generate code documentation using dokka 🛩️

**Comment by wangerekaharun** [comment]
Cool will find time and work on this and refactor from using comments approach that is currently in place.

**Comment by wangerekaharun** [comment]
Closed by #72
